package it.laitspa.cpf.service.security;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-03-31T16:04:44.454+02:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "SecurityService", 
                  wsdlLocation = "https://www.laitspa.it/cpf/services/Security?wsdl",
                  targetNamespace = "http://security.service.cpf.laitspa.it") 
public class SecurityService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://security.service.cpf.laitspa.it", "SecurityService");
    public final static QName SecuritySoap11Binding = new QName("http://security.service.cpf.laitspa.it", "SecuritySoap11Binding");
    static {
        URL url = null;
        try {
            url = new URL("https://www.laitspa.it/cpf/services/Security?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SecurityService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://www.laitspa.it/cpf/services/Security?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SecurityService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SecurityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecurityService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SecurityService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SecurityService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SecurityService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Security
     */
    @WebEndpoint(name = "SecuritySoap11Binding")
    public Security getSecuritySoap11Binding() {
        return super.getPort(SecuritySoap11Binding, Security.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Security
     */
    @WebEndpoint(name = "SecuritySoap11Binding")
    public Security getSecuritySoap11Binding(WebServiceFeature... features) {
        return super.getPort(SecuritySoap11Binding, Security.class, features);
    }

}
