package it.laitspa.cpf.service.ricezioneordini;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-04-03T15:08:56.764+02:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://ricezioneordini.service.cpf.laitspa.it", name = "RicezioneOrdini")
@XmlSeeAlso({ObjectFactory.class})
public interface RicezioneOrdini {

    @WebMethod(action = "rifiutaOrdine")
    @RequestWrapper(localName = "rifiutaOrdine", targetNamespace = "http://ricezioneordini.service.cpf.laitspa.it", className = "it.laitspa.cpf.service.ricezioneordini.RifiutaOrdine")
    @ResponseWrapper(localName = "rifiutaOrdineResponse", targetNamespace = "http://ricezioneordini.service.cpf.laitspa.it", className = "it.laitspa.cpf.service.ricezioneordini.RifiutaOrdineResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.laitspa.cpf.service.ricezioneordini.RifiutoResult rifiutaOrdine(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "codiceOrdine", targetNamespace = "")
        java.lang.Integer codiceOrdine,
        @WebParam(name = "motivo", targetNamespace = "")
        java.lang.String motivo
    );

    @WebMethod(action = "confermaOrdine")
    @RequestWrapper(localName = "confermaOrdine", targetNamespace = "http://ricezioneordini.service.cpf.laitspa.it", className = "it.laitspa.cpf.service.ricezioneordini.ConfermaOrdine")
    @ResponseWrapper(localName = "confermaOrdineResponse", targetNamespace = "http://ricezioneordini.service.cpf.laitspa.it", className = "it.laitspa.cpf.service.ricezioneordini.ConfermaOrdineResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.laitspa.cpf.service.ricezioneordini.ConfermaResult confermaOrdine(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "codiceOrdine", targetNamespace = "")
        java.lang.Integer codiceOrdine
    );

    @WebMethod(action = "listaOrdiniDaPrelevare")
    @RequestWrapper(localName = "listaOrdiniDaPrelevare", targetNamespace = "http://ricezioneordini.service.cpf.laitspa.it", className = "it.laitspa.cpf.service.ricezioneordini.ListaOrdiniDaPrelevare")
    @ResponseWrapper(localName = "listaOrdiniDaPrelevareResponse", targetNamespace = "http://ricezioneordini.service.cpf.laitspa.it", className = "it.laitspa.cpf.service.ricezioneordini.ListaOrdiniDaPrelevareResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.laitspa.cpf.service.ricezioneordini.ListaResult listaOrdiniDaPrelevare(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    );

    @WebMethod(action = "prelevaOrdine")
    @RequestWrapper(localName = "prelevaOrdine", targetNamespace = "http://ricezioneordini.service.cpf.laitspa.it", className = "it.laitspa.cpf.service.ricezioneordini.PrelevaOrdine")
    @ResponseWrapper(localName = "prelevaOrdineResponse", targetNamespace = "http://ricezioneordini.service.cpf.laitspa.it", className = "it.laitspa.cpf.service.ricezioneordini.PrelevaOrdineResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.laitspa.cpf.service.ricezioneordini.PrelevaResult prelevaOrdine(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "codiceOrdine", targetNamespace = "")
        java.lang.Integer codiceOrdine
    );

    @WebMethod(action = "ricercaOrdini")
    @RequestWrapper(localName = "ricercaOrdini", targetNamespace = "http://ricezioneordini.service.cpf.laitspa.it", className = "it.laitspa.cpf.service.ricezioneordini.RicercaOrdini")
    @ResponseWrapper(localName = "ricercaOrdiniResponse", targetNamespace = "http://ricezioneordini.service.cpf.laitspa.it", className = "it.laitspa.cpf.service.ricezioneordini.RicercaOrdiniResponse")
    @WebResult(name = "return", targetNamespace = "")
    public it.laitspa.cpf.service.ricezioneordini.ListaResult ricercaOrdini(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token,
        @WebParam(name = "documentIdVersion", targetNamespace = "")
        java.lang.String documentIdVersion,
        @WebParam(name = "codiceAzienda", targetNamespace = "")
        java.lang.String codiceAzienda,
        @WebParam(name = "dataDocumentoDa", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar dataDocumentoDa,
        @WebParam(name = "dataDocumentoA", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar dataDocumentoA,
        @WebParam(name = "dataImmissioneDa", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar dataImmissioneDa,
        @WebParam(name = "dataImmissioneA", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar dataImmissioneA
    );
}
